// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.5.3. SEE SOURCE BELOW. !!
pragma solidity 0.8.24;

import "./IUniswapV3Pool.sol";

struct BunniKey {
    IUniswapV3Pool pool;
    int24 tickLower;
    int24 tickUpper;
}

interface IBunniHub {
    struct DepositParams {
        BunniKey key;
        uint256 amount0Desired;
        uint256 amount1Desired;
        uint256 amount0Min;
        uint256 amount1Min;
        uint256 deadline;
        address recipient;
    }
    function deposit(DepositParams calldata params)
        external
        payable
        returns (
            uint256 shares,
            uint128 addedLiquidity,
            uint256 amount0,
            uint256 amount1
        );

    struct WithdrawParams {
        BunniKey key;
        address recipient;
        uint256 shares;
        uint256 amount0Min;
        uint256 amount1Min;
        uint256 deadline;
    }
    function withdraw(WithdrawParams calldata params)
        external
        returns (
            uint128 removedLiquidity,
            uint256 amount0,
            uint256 amount1
        );

    function compound(BunniKey calldata key)
        external
        returns (
            uint128 addedLiquidity,
            uint256 amount0,
            uint256 amount1
        );


    function protocolFee() external view returns (uint256);

    function setProtocolFee(uint256 value) external;

}


interface IBunniToken is IERC20 {
    function hub() external view returns (address);

    function pool() external view returns (IUniswapV3Pool);

    function tickLower() external view returns (int24);

    function tickUpper() external view returns (int24);
}
interface IBunniLens {
    function getReserves(BunniKey calldata key)
        external
        view
        returns (uint112 reserve0, uint112 reserve1);
}

// address constant      launcher = 0x1aF32A033fFF8b1136D6499672C508C4C8813eC9;
// address constant       launcher = 0xE9e648a546C07F5503BFd89153e5594904Ff47eE; // old 
// IBunniHub constant    hub = IBunniHub(0xb5087F95643A9a4069471A28d32C569D9bd57fE4);

address constant GRAI = 0x15f74458aE0bFdAA1a96CA1aa779D715Cc1Eefe4;
address constant UNI = 0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984;
address constant WBTC = 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599;
address constant SGT = 0x24C19F7101c1731b85F1127EaA0407732E36EcDD;
address constant BADGER = 0x3472A5A71965499acd81997a54BBA8D852C6E53d;
address constant GHO = 0x40D16FC0246aD3160Ccc09B8D0D3A2cD28aE6C2f;
address constant APE = 0x4d224452801ACEd8B2F0aebE155379bb5D594381;
address constant LINK = 0x514910771AF9Ca656af840dff83E8264EcF986CA;
address constant LDO = 0x5A98FcBEA516Cf06857215779Fd812CA3beF1B32;
address constant frxETH = 0x5E8422345238F34275888049021821E8E08CAa1f;
address constant LUSD = 0x5f98805A4E8be255a32880FDeC7F6728C6568bA0;
address constant DAI = 0x6B175474E89094C44Da98b954EedeAC495271d0F;
address constant LQTY = 0x6DEA81C8171D0bA574754EF6F8b412F2Ed88c54D;
address constant MATIC = 0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0;
address constant FRAX = 0x853d955aCEf822Db058eb8505911ED77F175b99e;
address constant USDC = 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48;
address constant PAL = 0xAB846Fb6C81370327e784Ae7CbB6d6a6af6Ff4BF;
address constant sfrxETH = 0xac3E018457B222d93114458476f3E3416Abbe38F;
address constant rETH = 0xae78736Cd615f374D3085123A210448E74Fc6393;
address constant WETH = 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2;
address constant AURA = 0xC0c293ce456fF0ED870ADd98a0828Dd4d2903DBF;
address constant USDT = 0xdAC17F958D2ee523a2206206994597C13D831ec7;
address constant swETH = 0xf951E335afb289353dc249e82926178EaC7DEd78;
address constant LIT = 0xfd0205066521550D7d7AB19DA8F72bb004b4C341;
address constant DOP = 0x6bB61215298F296C55b19Ad842D3Df69021DA2ef;
address constant EURe = 0x3231Cb76718CDeF2155FC47b5286d82e6eDA273f;
address constant DOLA = 0x865377367054516e17014CcdED1e7d814EDC9ce4;
address constant pxETH = 0x04C154b66CB340F3Ae24111CC767e0184Ed00Cc6;
address constant rswETH = 0xFAe103DC9cf190eD75350761e95403b7b8aFa6c0;
address constant INV = 0x41D5D79431A913C4aE7d69a668ecdfE5fF9DFB68;



uint256 constant PRICE_UNI = 1214000000;
uint256 constant PRICE_WBTC = 4302100000000;
uint256 constant PRICE_SGT = 15000000;
uint256 constant PRICE_BADGER = 200000000;
uint256 constant PRICE_GHO = 96500000;
uint256 constant PRICE_LDO = 155000000;
uint256 constant PRICE_USDC = 99700000;
uint256 constant PRICE_INV = 3677000000;
uint256 constant PRICE_DOLA = 177000000;
uint256 constant PRICE_fraxETH = 164277000000;
uint256 constant PRICE_sfraxETH = 173877000000;
uint256 constant PRICE_WETH = 328000000000;
uint256 constant PRICE_AURA = 74684700;
uint256 constant PRICE_LQTY = 145600000;
uint256 constant PRICE_USDT = 100000000;
uint256 constant PRICE_FRAX = 99600000;
uint256 constant PRICE_PAL = 10500000;
uint256 constant PRICE_swETH = 168200000000;
uint256 constant PRICE_LUSD = 99400000;
uint256 constant PRICE_GRAI = 99400000;
uint256 constant PRICE_EURe = 105100000;
uint256 constant PRICE_LIT = 3100000;

address constant WETH_TAI = 0xA88a7820c43992b6f3804Ed875cd0dA8911C683e;
address constant GRAI_USDC = 0x380Bdc6aED21f4fF029e4577244dD1CB0400b618;
address constant boxETH_WETH = 0xdd57f07aD41940800c91a5cF7BEAef7EBe8aD4D9;
address constant SGT_WETH = 0xA6cCB9029401565343beE9f63c6963935747Ff30;
address constant LDO_WETH = 0x91d8f2CeA8AEfAD1B158ACd8B4d2DBD91Be52719;
address constant WBTC_BADGER = 0x849535B729768321ADeD4EdE1aCEfa03a5f96FDE;
address constant DCHF_USDC = 0x93F262B15D06af1aD3f20adb6E68E1E5D445e098;
address constant JBX_WETH = 0x8E53f39a724A34Ea3e3097d9d347d1d81AD9240E;
address constant GHO_USDC = 0x222D24406cd28d1B62d35f8a35C77A3bdDc01Cf7;
address constant WETH_AMKT = 0x12C54EC4a2ff465Af7852F48c3CBF1A6c620d94d;
address constant DOP_WETH = 0x71044da4d6ea08E59f56970f914588760f76baa7;
address constant EURe_USDC = 0x532aD5EA77fad346962E1E364aF8CE7b679502f5;
address constant MON_WETH = 0xD92B9de5CA357754B9DBE1599aa57ba87B76455E;
address constant LQTY_WETH = 0x784f3f56D804CeE28881f3bd88e0cFC8Be6634Ac;
address constant DCHF_USDC_2 = 0xBD28Cda9b106315083fCAA80609b8DAc4BfB8e08;
address constant KC_WETH = 0x871b4Eb432bD2F57c695776E07d7c4a4aC46e0F0;
address constant UNI_WETH = 0x15C019f18f9C0088400b87C6383B6272792b9ec1;
address constant USDC_USDT = 0x883C8F841a165E1A427B69B0D55fB1CbcA501052;
address constant frax_WETH = 0xefFe49D9fCe8A4fC71Be42f7b2A83Bd353107Be3;
address constant WETH_AURA = 0x30d789c93aAB4E70a307e546ca3265B0a6572E64;

address constant WETH_LIT = 0x55f345F2D01024b6485fe2700f0F05f60b015b0F;
address constant LUSD_USDC = 0x578D512C657F8Bd7BB77Ea7825795381494c979D;
address constant LUSD_USDC_2 = 0x1f28E924dD068F671B787Ba8E3e33d544685cDdF;
address constant WETH_swETH = 0x846A4566802C27eAC8f72D594F4Ca195Fe41C07a;
address constant WETH_swETH_2 = 0xa9405630dC8bBbC840BeDc1dD4e61d68CE0229c5;
address constant WETH_swETH_3 = 0x05058071E3E799f0C6341F44843636e7c441c1fB;
address constant WETH_swETH_4 = 0xcafdd596628412B8f0f02a707752F0B20f5C453D;
address constant FRAX_PAL = 0x42Db14bfd6a72Ab8a3806193BC9b4419D8d503c8;
address constant FRAX_USDC = 0x088DCFE115715030d441a544206CD970145F3941;
address constant GRAI_swETH = 0x7481607303B4d0493023888309Ef4a7249500afB;

address constant BUNNI = 0x000000C396558ffbAB5Ea628f39658Bdf61345b3;

interface IWETH9 is IERC20 {
  function deposit() external payable;

  function withdraw(uint256 wad) external;
}


interface IMigrator {
    function migrate(uint256 oldTokenAmount, address recipient) external returns (uint256 newTokenAmount);
}

address constant  migrator = 0x000000c2552ac621A551170d95B5ae6CB97Ad811;
