from_addr="0x8856c1E1b30C0CBa94032F8C97c5aFC5cf3B104D"
to_addr="0x8dfb6fcB65830EbAC54D92f1aD170aF01B0AC10f"
simulator_addr="0xdcA45FAC69E4D82FeA917E3338B0dC1545C6fA46"
rpc_url = "http://65.21.96.142:8545"
mevshare_url=""
sequencer_url = "https://mainnet-sequencer.base.org"
ws_url = "ws://65.21.96.142:8546"
flashblocks_url = "wss://mainnet.flashblocks.base.org/ws"
trade_server_url = "65.21.96.142:8829"
data="../contract/operator_8"
chain_id=8453
gas_limit=7000000
test_mode=false
simulation_mode=false
exeuction_mode=true
step_count=50
regression_count=7
simulate_interval=10
min_profit=1
min_swap_amount=15000