chain_id = 10
from_addr="0xB9f1a14E1d14C5265447DE1d8A417BeA3BaA5A7e"
to_addr="0x34a16Bb5ACFBDc39799adb8DeCF05f7ef8FeD9fe"
simulator_addr="0x0D42285a56c22Df036ac94B43eACfE9Bfd0ACdba"
rpc_url = "http://localhost:6546"
ws_url = "ws://localhost:6546"
mevshare_url=""
sequencer_url = "https://mainnet-sequencer.optimism.io"
data="./b"
test_mode=false
gas_limit=7000000
step_count=40
regression_count=6
simulate_interval=50